// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_service.proto

package cn.egg.tutorial.demo.service;

public final class GreetingService {
  private GreetingService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023hello_service.proto\022\031cn.egg.tutorial.d" +
      "emo.grpc\032\013hello.proto2m\n\014HelloService\022]\n" +
      "\010sayHello\022\'.cn.egg.tutorial.demo.grpc.He" +
      "lloRequest\032(.cn.egg.tutorial.demo.grpc.H" +
      "elloResponseB1\n\034cn.egg.tutorial.demo.ser" +
      "viceB\017GreetingServiceP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.egg.tutorial.demo.grpc.model.Hello.getDescriptor(),
        }, assigner);
    cn.egg.tutorial.demo.grpc.model.Hello.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
