// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package cn.egg.tutorial.demo.grpc.model;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.egg.tutorial.demo.grpc.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
