// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package cn.egg.tutorial.demo.grpc.model;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.egg.tutorial.demo.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   */
  int getId();
}
